apiVersion: v1
description: IBM DataPower Gateway B2B
home: http://www-03.ibm.com/software/products/en/datapower-gateway
icon: https://avatars1.githubusercontent.com/u/8836442?v=4&s=200
keywords:
- DataPower
- Gateway
- B2B
- Security
- IDG
name: ibm-datapower-b2b
tillerVersion: '>=2.8.0'
version: 0.0.8
